[build]
  command = "npx puppeteer browsers install chrome && npm run build"
  publish = "build"

[[redirects]]
  from = "/cista-mzda"
  to = "/cista-mzda/"
  status = 200
  force = true

[[redirects]]
  from = "/pujcka"
  to = "/pujcka/"
  status = 200
  force = true

[[redirects]]
  from = "/rocni-dane"
  to = "/rocni-dane/"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
